//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.Media = new HashSet<Medium>();
            this.Reviews1 = new HashSet<Review>();
        }
    
        public long Id { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string UserId { get; set; }
        public Nullable<byte> Rate { get; set; }
        public string Text { get; set; }
        public Nullable<long> ReviewId { get; set; }
        public Nullable<bool> Publish { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medium> Media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews1 { get; set; }
        public virtual Review Review1 { get; set; }
        public virtual Room Room { get; set; }
    }
}
